name: safehaven
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  http: ^1.2.1
  shared_preferences: ^2.0.9
  geolocator: ^12.0.0
  google_maps_flutter: ^2.1.0
  firebase_core: ^1.10.6
  firebase_auth: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
